language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    -   secure: "DBea82Jw9/XIEDf6gs11I80QDKeEdzg6+zDf61tLR+98XtmSx3kdiEIO/rLQ0aF78/PIZ7nanntOJueEdzE4QO6843BoFC5GP0DgiXD+pamvBVjcaiN4pVZzWAiYRjbWvVSvtAwLZ/lCwW2xBKVEn6Sjpo1R0EgJnAz2sDzc/t6kTRHEh4ExDozDOLfW1mPgcSWeSivmOo4qwGO2b7XC6RN8mqGRjwWF6H1wRsoLL5wMVz4EVN3hpM7IWFrEUiuXLqtvpIMsrm5dxgcBzvjhuWi3hE46ak2GMLZCdWTsWIb6D9IHnL8e5tawI9d7cz5JOZttuzNCjT9goQ9VmSYLICzzyeEvxOymOFvQwotLCM9bbVm7pELxDCR1EXGg+LytWTJ0vK7pOa9LGlXCldSt+Y57C0la0AenXP0vgjVP85ipQLaw06TV/DbKw70S7bMINdggOiKH4j+xiKMaUX4yGDmt+YlNqJhF7YsG9JQQUtz4F4rxXnSuCI4TM03/NXNXki1w6tnJkGUSFaS8d3aqfH0YJflVZKJ18szP/T6X+AhjIt7QnVZ1OJyOtTeMqpAL9r3FIn4tgT9gu0vHOeKkjQlNj/PbFsJR52qUYQTm5EucvhgRivfjQPT3PNg0dClUpaY1QGbC4K0lP2zR+el9qsvT5ypZi7LmOd8u6lxP+Gw="
    - # ^^ OSSRH_PASSWORD
    - secure: "WziifCswYPd+zZO5HQmpmr4YmFGh9v/dPf/TKFMp56564wVvmIbgTBq3hw8R0hBpBVltEgXzWHI2E7CuZghIdbBD7cToL+AMhoVPCpwRBeF1WWwH1lzmAIUYoEhL3V+BguTSn4FiqgvmLZr6tjwDoeqb17lKREb0Fogfpi6ZwAGrkWdU4w8QpqFoHossGIKgWtLrp8qzBfeS8Ga73r3x5rO2fjSYva/7zZTmyd+3+WUovvMrJYyw9wxWFvP7ja8qY0oSnKo3BF3tgu/OG2DJlEUuwtHHAMUG4N3WtNNKFm1pukK/12WFmf8rsH7fGRoz3+e6sV2d5frHSqS7MGUXgIEDE6pzxP35Z6wJx/79anW+KL7QMlsUW0ZWoDz9K6+n2pOfnUBGv/pRzMsTnA0Uwb8GR+1f0BpjiArv8c7nOgqECe5NWF9gMU1cO99x2OQAFrxLuMEy1/hluRnsV1/B2B6Ci5Q1ELZn48PODAvAYOCZQMPMxI4WqnP777LO/8+5Sx4Hr5JF6kB6jhbxfQlDJ/0gLGKJt0l+6SAfGsfuMjI4wRWm0QIgbTWZKcMMt/gbaAQeiq/LkgzocF5MMkv8QsiLBIynB55pYL5XSL0VdV24teTGtFK2zMDVTvO5MTI6bIxuA5vFwuWjzT8aKWjAJSJM8sDI1jTE+QHBPsUK1Mk="
    - # ^^ GPG_KEY_NAME
    - secure: "uSaQl8FrWKkMJrDy+Z0WjT7F0dADFnk1R0rBQvedmYNwW8vtFzJ3gLSq6smXVC9yrKqRHO6h8/iP7wXsb6gIU2wMRvDwiXLL/8vi9Cf80MSbxkl2PIdINX+OnIKySBOVT2pQU2bCaj/rS5I4OVzOghuoYn4O3r8Sayul9nERSEm7WAOshdDRF+MnQDxnryLCdtEJ8hD/wO8JR2Ex1ebElgKzKJJs78SDLLddV8wTiSIMyui96lhwC23KPPAio0n5pC296jjcc9VykzqJ7WIt/pPPK0paqEZpNh8hx3phqwm9YdC4uAA3oG2fGNOYc4UMtZXl9P79e9vv2YSkh37iaY3PoNJEsXoJ4xwHONj1x19Lu/ZdxiRWi1+1sOVarhmaCpI6LY3s3jO4SdnZmld7IBi9mjVyexAm3o3xU3P7NwZ62vOhrVruvMw7OjB9UyJZs2YTD33/gg+CDY14gJXORNPIFDLieKWeVjTGP169tMGpnCe7Utm6Dp3FebUSIkOM5ssjcK22iXRs6wFRmPDV2TRdXKIv+IbaCVPIfMRMqLJHfKjtUANnBPPi7AxSmbdsrwrZ+n+NV9z2eyhyW4niYLdMAvQUE5LivckTdWu82QuZ9WLHuinkU7KCClQxSc8H4WnPci8GQJL04Lxh2Ec0Mh9OBwFEiA77JdErI1UmX18="
    - # ^^ GPG_PASSPHRASE
    - secure: "Auhz2/0OtHu2DYPqFGUp2cWvgyJT1zsVjfaUcmJjaoOKEu0zI60YG9xyE6+C96W/LWtUwEMq16Kn+GZRnslHLgew43mB2n0DxuWcHT1tklbwCBkvqi7rnypKLsNMZEC5nHR7HR8/bKHm61T+9A91SIpi6iXuWfE71HwUPt88d9VzeNIUf2iodjMOyKcZixndmL868a2hKrzMOkBkhnZKH5BSVSE39G6EBNd1/qiFFCYFVEiCYZS8Q4Acri7Nb3bQBjK0YQ5yBweUvvJX9rHfpQYIGNMwFZqAmQA57mUb0hMl1/3vPYP98mDJ0Y528NLdsfTsKqFn6gWD0LAAe2Nz2ZkHka8hpbhx5KFEx2Ch8ZVuaOlLw8uXyzNAplH+XmrBxila1QPB068MajvjikaSajDJg4hntfCISwNiHGOhhCNls/ZeAK/W8P3Dw2i4MEgNFB+u9Wjy1qn261Pii0Y9kKQZntu6r5zf3EEwjgYAyQVloB9kVoFxS5usGGKaTEh1GytLttFqchUAtdkDCL4iiiE829edp5wTwctCDaECgI3s/76d3com0xlaOYFfIDiOjtrcJ05MdYQJm5NCZv1Xvm+2ML53iAIOWT2nCNqc+pomlnPikQLIZrl0LQPQtkYVKygUlDD9gAo/fisIHKR67Uo53ZHZcFQ8vOD9tYw/N8s="
    - # ^^ GITHUB_TOKEN
    - secure: "BRiLpW1lddg94OdgktcdubN2U0qszaXL8Bf5Hagu3oqY0KspKkFdN9cpdFiSRrzBlu3Z9BkfPxDzExvd4rHE+E1+yyXnYRIthkkHE042bmQzJSCDTSUxyncKfbN53L90VhldCPQD9Hk2vOCMTaPKg+abGr//G1R6j7fB9ggM5xZ1eE1YRTzhaJp2GsOA4Zud4+q/zwbSwkeVU00Be/G7MaGcYvHtIPBF6Z8vvdPCpCrqGfMhdZTZimWO+sUERuPbEiUHDOUKL5N0I2A0k+ibYJQw+zSswFJ3rZKPWgd4iGoM86+SXwXl26ao2obWf2KM8ox1ig4oJiYk1aPAsk05h7/4YCd63sVD80khBUQ81O19fgN2tyI4TY2CrRY/Irr0H6cY9sMBVIjPEiilZN/HEE7BBIlemcx1uDedHRfzW4pqYcHk7AhAqCsz4auEKqoT1MOlZB0hZxDxDFgmVU/yt1E/MUqTZ3sL19DoNeMnIqlJTSVi6Zt3p2oLyBWf0imisExNYvG2Azzuy9vDtw2RSlhVn/eTcKDF8TmcfFQ7wNhMSLzRPeIEaTK153jtkfYn3p/mXCdbHRe4ivhFVO1tUZrhN8CfsNTTtQ0LEs9y1IoOZHIJRWW6XJGsfWiCj+BcbK+qYf7oBTljHFk1e8qXsuwqwENh1eabLebto2HbY2o="
jdk:
  - oraclejdk8
before_install:
  - source ci/setup-git.sh
install: mvn clean install -P !ossrh -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U  --settings ci/mvnsettings.xml
script: mvn verify -P !ossrh -B --settings ci/mvnsettings.xml
after_failure:
  - find . -size +1k -regex  ".*/surefire-reports/.*\.txt" -exec cat {} +
cache:
  directories:
    - ~/.m2/repository
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  - provider: script
    skip-cleanup: true
    script: bash ci/mvn-release.sh
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script: bash ci/mvn-deploy.sh
    on:
      branch: develop
  - provider: script
    skip-cleanup: true
    script: bash ci/mvn-deploy.sh
    on:
      tags: true
addons:
  apt:
    packages:
    - libxml2-utils